spring.application.name=service

spring.datasource.url=jdbc:postgresql://localhost:5432/fittrack_db
spring.datasource.username=postgres
spring.datasource.password=vlado
spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true